### ISSUE TITLE
显示subtitle

### ISSUE THREAD

**Issue by wimvogt** [yscoder/hexo-theme-indigo#119]
当我打开除主页之外的页面时，头部的subtitle没有显示，该怎么设置成一直显示状态

**Comment by yscoder** [comment]
你说的浏览器标签显示？

**Comment by wimvogt** [comment]
不是，我说的是博客标题下面的介绍文字，https://wimvogt.github.io/，在首页的时候会有显示，在其它的页面中就消失了

**Comment by yuangezhizao** [comment]
其他页面博客标题不是换成文章标题了吗？自然就没有博客的副标题了吧。

**Comment by yscoder** [comment]
你说的是分类、归档这些页面吧，确实没有。

**Comment by wimvogt** [comment]
那如果我想要在这些页面也显示的话，应该怎么修改？

**Comment by yscoder** [comment]
[header.ejs#L32](https://github.com/yscoder/hexo-theme-indigo/blob/83c8feca97225503315c6b56eb0bb7345d462c2b/layout/_partial/header.ejs#L32) 把判断条件改下

```js
is_home() || is_archive() || is_category() || is_tag() || page.layout === 'categories' || page.layout === 'tags'
```

**Comment by wimvogt** [comment]
不行，hexo g的时候就会报错

**Comment by yscoder** [comment]
错误消息是什么？

**Comment by wimvogt** [comment]
Unhandled rejection TypeError: /Users/wim/hexo/themes/indigo/layout/archive.ejs:1
 >> 1| <%- partial('_partial/header', {
    2|     title: theme.archives_title,
    3|     hdClass: 'archives-header'
    4| }) %>

/Users/wim/hexo/themes/indigo/layout/_partial/header.ejs:38
    36|                 <%- page.description %>
    37|             <% } else { %>
 >> 38|                 <%- partial('post/head-meta') %>
    39|             <% }%>
    40|
    41|         </h5>

/Users/wim/hexo/themes/indigo/layout/_partial/post/head-meta.ejs:2
    1| <time datetime="<%= date_xml(page.date) %>" itemprop="datePublished" class="page-time">
 >> 2|   <%= page.date.format(config.date_format) %>
    3| </time>
    4|
    5| <% if (page.categories && page.categories.length){ %>

Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:171)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:53)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2065)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:33)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:52:560)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/wim/hexo/node_modules/bluebird/js/release/method.js:15:34

Unhandled rejection TypeError: /Users/wim/hexo/themes/indigo/layout/archive.ejs:1
 >> 1| <%- partial('_partial/header', {
    2|     title: theme.archives_title,
    3|     hdClass: 'archives-header'
    4| }) %>

/Users/wim/hexo/themes/indigo/layout/_partial/header.ejs:38
    36|                 <%- page.description %>
    37|             <% } else { %>
 >> 38|                 <%- partial('post/head-meta') %>
    39|             <% }%>
    40|
    41|         </h5>

/Users/wim/hexo/themes/indigo/layout/_partial/post/head-meta.ejs:2
    1| <time datetime="<%= date_xml(page.date) %>" itemprop="datePublished" class="page-time">
 >> 2|   <%= page.date.format(config.date_format) %>
    3| </time>
    4|
    5| <% if (page.categories && page.categories.length){ %>

Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:171)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:53)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2065)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:33)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:52:560)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/wim/hexo/node_modules/bluebird/js/release/method.js:15:34

Unhandled rejection TypeError: /Users/wim/hexo/themes/indigo/layout/archive.ejs:1
 >> 1| <%- partial('_partial/header', {
    2|     title: theme.archives_title,
    3|     hdClass: 'archives-header'
    4| }) %>

/Users/wim/hexo/themes/indigo/layout/_partial/header.ejs:38
    36|                 <%- page.description %>
    37|             <% } else { %>
 >> 38|                 <%- partial('post/head-meta') %>
    39|             <% }%>
    40|
    41|         </h5>

/Users/wim/hexo/themes/indigo/layout/_partial/post/head-meta.ejs:2
    1| <time datetime="<%= date_xml(page.date) %>" itemprop="datePublished" class="page-time">
 >> 2|   <%= page.date.format(config.date_format) %>
    3| </time>
    4|
    5| <% if (page.categories && page.categories.length){ %>

Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:171)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:53)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2065)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:33)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:52:560)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/wim/hexo/node_modules/bluebird/js/release/method.js:15:34

Unhandled rejection TypeError: /Users/wim/hexo/themes/indigo/layout/tag.ejs:1
 >> 1| <%- partial('tags', {
    2|     title: theme.tags_title + ': '+ page.tag
    3| }) %>

/Users/wim/hexo/themes/indigo/layout/tags.ejs:1
 >> 1| <%- partial('_partial/header', {
    2|     title: locals.title || theme.tags_title,
    3|     hdClass: 'tags-header'
    4| }) %>

/Users/wim/hexo/themes/indigo/layout/_partial/header.ejs:38
    36|                 <%- page.description %>
    37|             <% } else { %>
 >> 38|                 <%- partial('post/head-meta') %>
    39|             <% }%>
    40|
    41|         </h5>

/Users/wim/hexo/themes/indigo/layout/_partial/post/head-meta.ejs:2
    1| <time datetime="<%= date_xml(page.date) %>" itemprop="datePublished" class="page-time">
 >> 2|   <%= page.date.format(config.date_format) %>
    3| </time>
    4|
    5| <% if (page.categories && page.categories.length){ %>

Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:171)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:53)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2065)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:33)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:95)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
这个

**Comment by yscoder** [comment]
看一下你改的代码

**Comment by wimvogt** [comment]
<div class="container">
        <h1 class="title"><%=title %></h1>
        
        <%  if(is_home() || page.layout === 'page') { %> 
        <h5 class="subtitle">
            
            <% if('subTitle' in locals){ %>
                <%- config.subtitle %>
            <% } else if (page.description) {%>
                <%- page.description %>
            <% } else { %>
                <%- partial('post/head-meta') %>
            <% }%>

        </h5>
        <% } %>
    </div>
改成：
<div class="container">
        <h1 class="title"><%=title %></h1>

        <%  if(is_home() || is_archive() || is_category() || is_tag() || page.layout === 'categories' || page.layout === 'tags') { %> 
        <h5 class="subtitle">

            <% if('subTitle' in locals){ %>
                <%- config.subtitle %>
            <% } else if (page.description) {%>
                <%- page.description %>
            <% } else { %>
                <%- partial('post/head-meta') %>
            <% }%>

        </h5>
        <% } %>
    </div>
只改了这行<%  if(is_home() || is_archive() || is_category() || is_tag() || page.layout === 'categories' || page.layout === 'tags') { %> ，改回来就好了

**Comment by yscoder** [comment]
你改错了，你把 [header.ejs](https://github.com/yscoder/hexo-theme-indigo/blob/83c8feca97225503315c6b56eb0bb7345d462c2b/layout/_partial/header.ejs) 中 `content-header` 部分全覆盖吧。

**Comment by wimvogt** [comment]
覆盖后没有效果

**Comment by yscoder** [comment]
还报错吗？

**Comment by wimvogt** [comment]
没报错了，但是副标题还是没有显示

**Comment by wimvogt** [comment]
可以了，我把container改成这样了<div class="container">
        <h 1 class="title"><%=title %></h1>
        <h 5 class="subtitle"><%- config.subtitle %></h5>
    </div>

**Comment by yscoder** [comment]
还原下，把 `subtitle` 内改成这样。

```ejs
<% if(is_post()){ %>
      <%- partial('post/head-meta') %>
<% } else if(is_home() || is_archive() || is_category() || is_tag() || page.layout === 'categories' || page.layout === 'tags'){ %> 
       <%- config.subtitle %>
<% } else if (page.layout === 'page' && page.description) {%>
       <%- page.description %>
<% } %>
```

**Comment by wimvogt** [comment]
好的，谢谢了！
