### ISSUE TITLE
服务器运行久之后git bash会报错，但是网站依旧可以正常访问

### ISSUE THREAD

**Issue by Wensibob** [yscoder/hexo-theme-indigo#159]
我的服务器是windows server 2012版本的，开启服务器，短时间内运行无任何问题，大概超过半天的话，git命令行就会列出错误信息，但是网站依旧可以正常访问，错误信息如下：
```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    at C:\blog\node_modules\hexo-server\lib\middlewares\route.js:27:11
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at C:\blog\node_modules\hexo-server\lib\middlewares\header.js:9:5
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at Function.handle (C:\blog\node_modules\connect\index.js:186:3)
    at Server.app (C:\blog\node_modules\connect\index.js:51:37)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```
估计是http版本的问题，差看hexo/package.json，内容如下：
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by yscoder** [comment]
难道你是直接用 `hexo server` 在服务器运行？

**Comment by Wensibob** [comment]
请教大神应该如何运行😭

**Comment by yscoder** [comment]
`hexo server` 只是用来本地测试查看，生产环境应该使用健壮的 WEB服务器运行，比如 windows 中的 IIS。
上传时只需要把 public 里生成的文件提交到服务器目录就可以了。

**Comment by Wensibob** [comment]
谢谢大神，我已经配置好了，不过多说的对话框好像有一点问题，
![duoshuo](http://www.wensibo.top/1.png)<br>
请问该怎么解决呢？谢谢

**Comment by yscoder** [comment]
更新主题

**Comment by Wensibob** [comment]
大神按照你的方法已经解决了，还有另外一个问题，就是404页面配置不成功。
按照教程，在hexo/source目录下新建404.html，
![](http://wensibo.top/img/path.png)
里面的内容为：<br>
```html
layout: false    
title: "温斯渤 | 404"
---
```
可是依旧不能成功，这是[我的网站]("www.wensibo.top" "_blank")，麻烦你了。谢谢。
