### ISSUE TITLE
page.tags.each is not a function

### ISSUE THREAD

**Issue by cjsoft** [yscoder/hexo-theme-indigo#20]
在page中添加了tags后会出现
page内容
```
---
title: 扫描线
date: 2016-04-30 11:32:04
tags: [fav]
---
<http://openinx.github.io/2013/01/01/plane-sweep-thinking/>
```

错误信息
```
Unhandled rejection TypeError: C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\themes\indigo\layout\layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <nav id="menu" <% if(is_post() && theme.hideMenu){ %>class="hide"<% } %> >

C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\themes\indigo\layout\_partial\head.ejs:24
    22|   <title><% if (title){ %><%= title %> | <% } %><%= config.title %> | <%= config.subtitle %></title>
    23|   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
 >> 24|   <%
    25|     var keyWords = config.keywords;
    26|     if(page.tags){
    27|       keyWords = [];

page.tags.each is not a function
    at eval (eval at <anonymous> (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:50:17)
    at eval (eval at <anonymous> (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:54:745)
    at C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.ejsRenderer (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Render.renderSync (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\lib\hexo\render.js:87:23)
    at View.renderSync (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\lib\theme\view.js:50:29)
    at Object.partial (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\lib\plugins\helper\partial.js:42:19)
    at eval (eval at <anonymous> (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:661)
    at C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.ejsRenderer (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Hexo.tryCatcher (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Hexo.<anonymous> (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\method.js:15:34)
    at C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\lib\hexo\render.js:51:21
    at tryCatcher (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\egwcy\Google 云端硬盘\cjsoft.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
使用hexo 3.1.1，nodejs版本v4.2.2

**Comment by cjsoft** [comment]
出错部分被窝改成了
```
<%
    var keyWords = config.keywords;
    if(page.tags){
      keyWords = [];
      for (var k in page.tags) {
        if (Array.isArray(page.tags[k])) break;
        console.log(page.tags[k].toString());
        keyWords.push(page.tags[k].toString());
      }
      /* page.tags.each(function(k){
        keyWords.push(k.name);
      }) */
      console.log(keyWords);
   }
  %>
```
tag数能对上，但是打上去的tag全是undefined
console.log的结果看上去没什么问题，
我想知道这部分该如何搞？
谢谢！

**Comment by yscoder** [comment]
> 只有文章 (post) 支持分类和标签。[Hexo文档链接](https://hexo.io/zh-cn/docs/front-matter.html#分类和标签)


虽然 page 中 tags 不会被 Hexo 标准支持，但仍然作为页面元数据存在。
Hexo 生成的 tags 对象是 `Object` 类型，page 中 tags 元数据是 `Array` 类型，最终在页面输出时需要的也是 `Array` 类型。可以据此判断来支持 page 中的 tags。

```
    var keyWords = config.keywords;
    if(page.tags){
      keyWords = [];
      
      _.isArray(page.tags) ? ( keyWords = page.tags ) 
        : page.tags.each(function(k){
            keyWords.push(k.name);
          });
   }
```

**Comment by cjsoft** [comment]
非常感谢您耐心的回复！、
