### ISSUE TITLE
更新了主题，编译不过了。

### ISSUE THREAD

**Issue by scriptstorm0809** [yscoder/hexo-theme-indigo#223]
YAMLException: duplicated mapping key at line 124, column -8:
    gitment:
    ^
    at generateError (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at storeMappingPair (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:307:7)
    at readBlockMapping (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1070:9)
    at composeNode (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at Hexo.yamlHelper (D:\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at D:\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)

**Comment by yscoder** [comment]
gitment 配置错了，贴一下看看

**Comment by scriptstorm0809** [comment]
还原了下，还好备份了下。
