### ISSUE TITLE
设置文内注解报错 TypeError

### ISSUE THREAD

**Issue by iljyya** [yscoder/hexo-theme-indigo#245]
设置文内注解报错 TypeError
```
test [^1]

[^1]: test
```

```
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:507:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at C:\blog\node_modules\hexo-server\lib\middlewares\route.js:27:11
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at C:\blog\node_modules\hexo-server\lib\middlewares\header.js:9:5
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at Function.handle (C:\blog\node_modules\connect\index.js:186:3)
    at Server.app (C:\blog\node_modules\connect\index.js:51:37)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:601:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

ps. 简书是可以的

**Comment by yscoder** [comment]
默认的 hexo-renderer-marked 插件不支持，可以尝试更换为 [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)
