### ISSUE TITLE
Unhandled rejection ReferenceError

### ISSUE THREAD

**Issue by ghost** [yscoder/hexo-theme-indigo#307]
执行hexo server后，访问[http://localhost:4000/](http://localhost:4000/)，终端抛出Unhandled rejection ReferenceError异常，请问大佬如何解决这个问题

```
Unhandled rejection ReferenceError: /home/kally/桌面/blog/themes/indigo/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html>
 >> 3| <%- partial('_partial/head') %>
    4| <body>
    5|     <%- partial('_partial/loading') %>
    6|     <%- partial('_partial/menu') %>

/home/kally/桌面/blog/themes/indigo/layout/_partial/head.ejs:51
    49|     <% } %>
    50|     <%- favicon_tag(theme.favicon) %>
 >> 51|     <link rel="stylesheet" href="<%- url_for(theme_css('/css/style', cache)) %>">
    52|     <script>window.lazyScripts=[]</script>
    53| 
    54|     <!-- custom head -->

theme_css is not defined
    at eval (eval at <anonymous> (/home/kally/桌面/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:112:25)
    at returnedFn (/home/kally/桌面/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/home/kally/桌面/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/kally/桌面/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/kally/桌面/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/kally/桌面/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/kally/桌面/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/home/kally/桌面/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/home/kally/桌面/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/kally/桌面/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/kally/桌面/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/kally/桌面/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kally/桌面/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kally/桌面/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/kally/桌面/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/kally/桌面/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/kally/桌面/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/kally/桌面/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kally/桌面/blog/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```   

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yscoder** [comment]
确认一下 node 版本是否 v6+

**Comment by ghost** [comment]
@yscoder谢谢你的帮助，等我回家我会看看
