### ISSUE TITLE
最新代码初始化报错

### ISSUE THREAD

**Issue by TianZonglin** [yscoder/hexo-theme-indigo#332]
H:\blog\blogs>hexo new page tags
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at H:\blog\blogs\node_modules\hexo\lib\hexo\index.js:230:17
    at tryCatcher (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\promise.js:638:18)
    at H:\blog\blogs\node_modules\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at H:\blog\blogs\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Created: H:\blog\blogs\source\tags\index.md
需要：
将H:\blog\blogs\node_modules\hexo-generator-json-content下的index.js首行加上"use strict";
Why?

**Comment by yscoder** [comment]
你的 nodejs 应该是 4.x，你需要升级 nodejs 版本了

**Comment by TianZonglin** [comment]
确实是的！没有注意自己node的版本，非常感谢~
