### ISSUE TITLE
部署过程 显示表格语法格式有误 

### ISSUE THREAD

**Issue by snorlaxse** [yscoder/hexo-theme-indigo#441]
```shell
➜  _posts git:(master) ✗ hexo g -d
INFO  Start processing
ERROR Process failed: _posts/DataMining-Review-Assignment/DataMining-Review-Assignment.md
YAMLException: end of the stream or a document separator is expected at line 8, column 8:
    | :----: | :--------------------------- ...
           ^
    at generateError (/Users/Captain/Documents/Captainzj.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/Captain/Documents/Captainzj.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/Users/Captain/Documents/Captainzj.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/Users/Captain/Documents/Captainzj.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/Captain/Documents/Captainzj.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at parseYAML (/Users/Captain/Documents/Captainzj.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/Users/Captain/Documents/Captainzj.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/Users/Captain/Documents/Captainzj.github.io/node_modules/hexo/lib/plugins/processor/post.js:52:20)
```

**Comment by snorlaxse** [comment]
把_posts/DataMining-Review-Assignment下的md文件删了就OK了
不知道是不是_post下的文件夹里不能放md文件
