### ISSUE TITLE
Card theme

### ISSUE THREAD

**Issue by yscoder** [yscoder/hexo-theme-indigo#94]
> 趁着周末折腾了两天。

## Update

1. 文章内容、各个列表都使用了卡片布局，除首页外的列表都使用了 双栏瀑布流；
2. 标签页有了变化，放到了 header 上，在PC端数量过多时通过开关按钮显示，移动端可以通过滑动来切换；
3. 增加 `categories/index.html` 支持，布局结构与新标签页一致；
4. 文章底部增加可自定义的版权说明信息或博主留言；
5. 文章页的分享从右侧移至文章底部；
6. 标签改为多颜色循环；
7. 文章内标题增加 `headerlink` 支持；
8. 所有修改都对多种屏幕尺寸适配。

## Preview

[Card theme](http://imys.net/)

## @

#35 #91 

旧的版本已经发布为 [v0.5.0](https://github.com/yscoder/hexo-theme-indigo/releases/tag/v0.5.0)，此次准备更新首个 v1.0，敬请期待！

**Comment by yscoder** [comment]
卡片主题已提交到 [card](https://github.com/yscoder/hexo-theme-indigo/tree/card) 分支。

**Comment by MJPiero** [comment]
刚想说，你的博客变成卡片的样式挺好看的~ 还打算也改成你那样的哈哈

**Comment by yscoder** [comment]
```
# 本地切到 card 分支
git checkout -b card

# 拉取
git pull origin card
```

**Comment by xdcxdc** [comment]
card 分支发现一个问题。 如果一篇文章没有使用markdown的#标记来生成标题，即TOC内容是空的，文章页面就会判断为未加载完成。具体表现为顶部红色进度条不断循环，打赏按钮与分享按钮点击无响应。

**Comment by yscoder** [comment]
@xdcxdc 打赏的问题已解决，还有你邮件中提到的一些问题，两个分支都更新过了。

**Comment by NoahDragon** [comment]
期待！

**Comment by yscoder** [comment]
Release [v1.1](https://github.com/yscoder/hexo-theme-indigo/releases/tag/v1.1-card)

**Comment by boolBit** [comment]
启动报错了 ERROR Script load failed: themes\indigo\scripts\plugins.js
SyntaxError: Unexpected token =
    at Object.exports.runInThisContext (vm.js:53:16)
    at C:\Users\Administrator\blogNew\node_modules\hexo\lib\hexo\index.js:227:17
    at tryCatcher (C:\Users\Administrator\blogNew\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._s

**Comment by yscoder** [comment]
@boolBit 升级 Node 6.x。另外与主题无关的内容要另开 issues。

**Comment by boolBit** [comment]
已解决 O(∩_∩)O谢谢
